### PR TITLE
Fix electron stability by switching from nan to node-addon-api

### LINKED ISSUE #176: Fix electron stability
Me again. As a follow up to #173 I wasn't able run this module in a stable fashion from inside electron. Besides immediate crashes I came as far a having a first successful render but a crash of the render process afterwards.

After reading a lot of documentation, source code, tutorials and howtos, I came to the conclusion that the used [nan](https://github.com/nodejs/nan) module to create the native addon is discouraged now and we better should use [node-addon-api](https://github.com/nodejs/node-addon-api). This is because the latter is at least independend of any volatile interface like the v8 types, makes addon initialization safe for multithreaded environments and also reentrant, etc.

So I reworked the addon using that said module and now it works. So far so good.

But: I am using the latest version of *node-addon-api* ([3.0.2](https://github.com/nodejs/node-addon-api/releases/tag/3.0.2) of 2020-09-18 at this point) and using an interface introduced in that release (namely *Napi::Addon*). I am not quite sure how backwards compatiblity is affected by my choice. Especially I could not find out the minimum required node version for my change.

Anyway, I'll prepare a PR. Feel free to ignore it if my choice isn't in your interest.

### PR DESCRIPTION
**Pull request by McShelby**
Fixes #176

### CODE REVIEW

**Comment by yanyiwu** [comment]
If it is merged, it may cause the version below 7.0.0 to fail. Are there many people using nodejs versions below 7.0?

**Comment by McShelby** [comment]
Hard to tell.

I see your module used as dependency for *a lot* of other chinese related node modules. That makes the impact hard to predict.

Node 6 was an LTS release and is unsupported since 2019-04-30.
[Node 7](https://nodejs.org/en/blog/release/v7.0.0/) is from late 2016.
Current Node LTS is 14.x
Electron 10 is using 12.x
Electron 8 (as used in VSCode) is also using 12.x

For me, this seems worth the risk.

**Comment by yanyiwu** [comment]
Thank you very much. If you are also a cryptocurrency enthusiast, for example, if you have an EOS account, I hope to transfer a little EOS tokens through the blockchain to express my gratitude forever.

**Comment by yanyiwu** [comment]
https://travis-ci.org/github/yanyiwu/nodejieba/builds/744923635

@McShelby after i taged v2.5.0 , it failed. it is weird because the code is unchanged. can you help to find out what's the problem ?

**Comment by McShelby** [comment]
Seariously puzzling. It may have something to do with the `--fallback-to-build` switch. But at the moment I am only guessing.

I was already wondering, that it worked with Node 7.1.0. I did not expect this. Now with this error, I have the fealing, that the travis job of my bugfix branch was using the precompiled version but did not run the compile at all.

**Pull request merged**
