### PR TITLE
Make module context-aware to be included in electron

### LINKED ISSUE #172: Make module Node-context-aware to be included in electron
To add this module in electron, it needs to be [context aware](https://github.com/electron/electron/issues/18397) in sense of a [node module](https://nodejs.org/api/addons.html#addons_context_aware_addons).

This means getting rid of `global_jieba_handle` inside of `nodejieba.cpp`

### PR DESCRIPTION
**Pull request by McShelby**
Fixes #172

### CODE REVIEW

**Comment by McShelby** [comment]
Implementation taken from the nan tests: https://github.com/nodejs/nan/blob/master/test/cpp/isolatedata.cpp

**Comment by McShelby** [comment]
Thanks for merging

**Comment by yanyiwu** [comment]
Thank you for your contribution

**Comment by yanyiwu** [comment]
https://github.com/yanyiwu/nodejieba/pull/175/files

**Pull request merged**
