### PR TITLE
upgrade to nan@2.0.0 and fix compatibility with iojs3

### LINKED ISSUE #36: iojs-3.0 安装失败
参考 https://travis-ci.org/hotoo/pinyin/jobs/75228439

### PR DESCRIPTION
**Pull request by PeterCxy**
this fixes compatibility with iojs@3.0.0 and close #36

tested in my project telegram-bot-language-chinese

Signed-off-by: Peter Cai <xqsx43cxy@126.com>

### CODE REVIEW

**Comment by PeterCxy** [comment]
however, nan2.0.0 requires a higher version of node.js and io.js, or the build will fail.

**Comment by PeterCxy** [comment]
Wait a minute, Travis fails. You need to drop some outdated node.js versions from Travis CI build list. nan@2.0.0 supports 0.8.27+, 0.10.29+, 0.12.0+, 1.0.0+, 2.0.0+ and 3.0.0+ only.

**Comment by hotoo** [comment]
...

**Comment by PeterCxy** [comment]
@hotoo Travis CI errors fixed in the new PR.

**Comment by yanyiwu** [comment]
@PeterCxy  Thank you very much

New version `nodejieba@1.3.0` published.

**Comment by Arthur2e5** [comment]
But why did you rename `args` to `info`..

**Pull request merged**
