### PR TITLE
Fix build error at Node.js v12

### PR DESCRIPTION
**Pull request by simon300000**
declaration: I have absolute 0 experience with C/C++ programming before this.
But this branch will build successfully at Node.js v12.3.1 at macOS 10.14.6

probably related to #131

reference:

https://github.com/tree-sitter/tree-sitter-bash/commit/97e13b8145c914b2efadfc03fc7c543729202ff1

https://github.com/fsevents/fsevents/pull/274

https://github.com/nodejs/nan/issues/849

https://github.com/nodejs/nan/blob/master/doc/converters.md

https://v8docs.nodesource.com/node-0.8/dc/d0a/classv8_1_1_value.html#a646846ac3a30fcc1477bc4727a3d4a59

### CODE REVIEW

**Comment by simon300000** [comment]
it seems only success at v10 and above at travis...

**Comment by simon300000** [comment]
I don’t know how to fix this problem;
So I remove `ValueToString` from `utils.h`.
nodejieba seems works fine without it?

Maybe a better PR is more suitable for solving this issue.

**Comment by simon300000** [comment]
I deleted package-lock.json because it is not in sync with package.json, thus crash the build.

**Comment by yanyiwu** [comment]
Thanks

**Pull request merged**
